# Generated by Django 6.0.7 on 2026-08-19 07:47

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(editable=False, help_text='Auto-generated application reference number.', max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=150)),
                ('guardian', models.CharField(max_length=150, verbose_name="Guardian's Name")),
                ('address', models.TextField()),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid contact number (7-15 digits, optional leading +).', regex='^\\+?\\d{7,15}$')])),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('OTHER', 'Other')], default='GEN', max_length=10)),
                ('highest_qualification', models.CharField(max_length=150)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email_or_phone', models.CharField(help_text='Accepts either an email address or a phone number.', max_length=150, verbose_name='Email / Phone')),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='admissionapplication',
            name='home_admiss_course__ce4973_idx',
        ),
        migrations.RemoveIndex(
            model_name='admissionapplication',
            name='home_admiss_status_d29dd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='home_blogpo_is_publ_489281_idx',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='responded_by',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='home_course_is_acti_ed89d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='home_course_categor_122710_idx',
        ),
        migrations.RemoveField(
            model_name='syllabusmodule',
            name='course',
        ),
        migrations.DeleteModel(
            name='InstituteProfile',
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-number']},
        ),
        migrations.RemoveIndex(
            model_name='notice',
            name='home_notice_is_publ_d13a8b_idx',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
        model_name='notice',
        name='number',
        field=models.PositiveIntegerField(default=1, editable=False, unique=True),
        preserve_default=False,
    ),
        migrations.AlterField(
            model_name='notice',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='course',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='SyllabusModule',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='AdmissionApplication',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
    ]
